---
title: 'WHO: Import Daily Reports'
author: "David J Jackson"
date: "3/23/2020"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(lubridate)
library(plotly)
```
```{r,echo=FALSE}
rm(list=ls())
```
```{r,echo=FALSE}

WHO <-dir("DATA",full.names=T) %>% map_df(fread)
colnames(WHO) <- c("State","Country","Update","Confirmed","Deaths","Recovered")

WHO$Year <- substr(WHO$Update,1,4)
WHO$Month <- substr(WHO$Update,6,7)
WHO$Day <- substr(WHO$Update,9,10)
WHO$Ymd <- as.Date(paste(WHO$Year, WHO$Month,WHO$Day, sep = "-"))
```
```{r, echo=FALSE}
WHO$Country <-ifelse(WHO$Country=="Mainland China","China",WHO$Country)
WHO$Country <-ifelse(WHO$Country=="Bolivia (Plurinational State of)","Bolivia",WHO$Country)
WHO$Country <-ifelse(WHO$Country=="Iran (Islamic Republic of)","Iran",WHO$Country)
# WHO$Country <-ifelse(WHO$Country=="Mainland China","China",WHO$Country)
```

```{r,echo=FALSE}
#
WHO_longitude <-dir("LongLat",full.names=T) %>% map_df(fread)
WHO_longitude$Year <- substr(WHO_longitude$Update,1,4)
WHO_longitude$Month <- substr(WHO_longitude$Update,6,7)
WHO_longitude$Day <- substr(WHO_longitude$Update,9,10)
WHO_longitude$Ymd <- as.Date(paste(WHO_longitude$Year, WHO_longitude$Month,WHO_longitude$Day, sep = "-"))
```
```{r,echo=FALSE}
WHO_long <-dir("LongData",full.names=T) %>% map_df(fread)
WHO_long$Year <- substr(WHO_long$Update,1,4)
WHO_long$Month <- substr(WHO_long$Update,6,7)
WHO_long$Day <- substr(WHO_long$Update,9,10)
WHO_long$Ymd <- as.Date(paste(WHO_long$Year, WHO_long$Month,WHO_long$Day, sep = "-"))
```

```{r, echo=FALSE}
# Combine Data sets
WHO_dat <- WHO %>% select(Ymd,State,Country,Update,Confirmed,Deaths,Recovered)
A <- WHO_longitude %>% select(Ymd,State,Country,Update,Confirmed,Deaths,Recovered)
B <- WHO_long %>% select(Ymd,State,Country,Update,Confirmed,Deaths,Recovered)
WHO_combined <- rbind(WHO_dat,A,B)
```

# Plot Total Cases by Country

```{r,echo=FALSE}
WHO_total_country <- WHO_combined %>% group_by(Country,Ymd) %>%                                 summarise(
                       TotalCases = sum(Confirmed),
                       TotalDeaths = sum(Deaths),
                       PercentDeaths =     TotalDeaths/TotalCases,
                                      Count = n())
```
```{r, echo=FALSE}

WHO_us <- WHO_total_country %>% filter(Country=="US")
WHO_world <- WHO_total_country %>% filter(Country !="US")

```
```{r,echo=FALSE}   
WHO_total_country_100 <- WHO_total_country %>% filter(TotalDeaths >100)
WHO_total_country_500 <- WHO_total_country %>% filter(TotalDeaths >500)
WHO_total_country_1000 <- WHO_total_country %>% filter(TotalDeaths >1000)
WHO_total_country_5000 <- WHO_total_country %>% filter(TotalDeaths >5000)
WHO_total_country_10000 <- WHO_total_country %>% filter(TotalDeaths >10000)
```
#### Total Confimed  Cases by Country

```{r,echo=FALSE}
 WHO_total_country_100  %>%
  ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases > 100") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
```

```{r,echo=FALSE}
 WHO_total_country_500  %>%
  ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases > 500") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
```
```{r, echo=FALSE}
# 
WHO_total_country_1000 %>% ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases >1000") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
```
```{r,echo=FALSE}
#
WHO_total_country_5000 %>% ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases > 5000") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
  
```
```{r,echo=FALSE}
#
WHO_total_country_10000 %>% ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases > 10000") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
  
```

```{r, echo=FALSE}
#
WHO_total_country_10000 %>% ggplot() + geom_col(aes(x=reorder(Country,TotalCases),y=TotalCases)) +
        labs(title ="Countries with Confirmed Cases > 10000") +
  coord_flip() + scale_y_continuous(labels = scales::comma) 
                                           
```

## Death Rate Percentage by Country 

```{r, echo=FALSE}
#### Total Confimed  Cases by Country
 WHO_total_country_500 %>% ggplot() +geom_col(aes(y=Country,x=PercentDeaths)) +
        labs(title ="Death Rate Percentage: Countries with Confirmed Cases > 500",x="Percentage of Confirmed Case That End in Death") +
        scale_x_continuous(labels=scales::percent) 

# 
WHO_total_country_1000 %>% ggplot() +geom_col(aes(y=Country,x=PercentDeaths)) +
        labs(title ="Death Rate Percentage:Countries with Confirmed Cases > 1000", 
        x="Percentage of Confirmed Case That End in Death") + 
        scale_x_continuous(labels=scales::percent)
#
WHO_total_country_5000 %>% ggplot() +geom_col(aes(y=Country,x=PercentDeaths)) +
        labs(title ="Death Rate Percentage: Countries with Confirmed Cases > 5000",        x="Percentage of Confirmed Case That End in Death") +              scale_x_continuous(labels=scales::percent)
        
#
WHO_total_country_10000 %>% ggplot() +geom_col(aes(y=Country,x=PercentDeaths)) +
        labs(title ="Death Rate Percentage: Countries with Confirmed Cases > 10000",
        x="Percentage of Confirmed Case That End in Death") +
        scale_x_continuous(labels=scales::percent)
                                           
```

#### US Vs World: Total Cases,Total Deaths, Death Rate

```{r,echo=FALSE}
World_total_daily <- WHO_world %>% group_by(Ymd) %>% summarise(
                                      TotalCases = sum(TotalCases),
                                      TotalDeaths = sum(TotalDeaths),
                                      DeathRate = TotalDeaths/TotalCases,
                                      Count = n())
```
```{r}
US_total_daily <- WHO_us %>% group_by(Ymd) %>% summarise(
                                      TotalCases = sum(TotalCases),
                                      TotalDeaths = sum(TotalDeaths),
                                      DeathRate = TotalDeaths/TotalCases,
                                      Count = n())
```

```{r, echo=FALSE}
ggplot() + geom_line(data=US_total_daily,aes(x=Ymd,y=TotalCases,col="US")) +
  geom_line(data=World_total_daily,aes(x=Ymd,y=TotalCases,col="World")) +
  scale_y_continuous(labels = scales::comma) +
  labs(title="US vs World: Total Confirmed Cases By Date")

ggplot() + geom_line(data=US_total_daily,aes(x=Ymd,y=TotalDeaths,col="US")) +
  geom_line(data=World_total_daily,aes(x=Ymd,y=TotalDeaths,col="World")) +
  scale_y_continuous(labels = scales::comma) + 
  labs(title="US vs World: Total Daeaths By Date")


ggplot() + geom_line(data=US_total_daily,aes(x=Ymd,y=DeathRate,col="US")) +
  geom_line(data=World_total_daily,aes(x=Ymd,y=DeathRate,col="World")) +
  labs(title="US vs World: Death Rate as  Percentage By Date") +
  scale_y_continuous(labels=scales::percent)
```


```{r}
country_total <- WHO_combined %>% group_by(Country,Ymd) %>% summarise(Count = n())
```

